// <auto-generated/> temporary ra ni na comment para walay warning sa stylecop i will remove this later

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace BridgCoreAPI.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}