// <auto-generated/> temporary ra ni na comment para walay warning sa stylecop i will remove this later

using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TestAPI
{
    public class Default : XPLiteObject
    {
        protected Default(Session session) : base(session)
        {

        }

        string lastName;
        string firstName;
        Guid oid;

        public Guid Oid
        {
            get => oid;
            set => SetPropertyValue(nameof(Oid), ref oid, value);
        }

        public string FirstName
        {
            get => firstName;
            set => SetPropertyValue(nameof(FirstName), ref firstName, value);
        }

        public string LastName
        {
            get => lastName;
            set => SetPropertyValue(nameof(LastName), ref lastName, value);
        }
    }
}
